# Site settings
title:                 Chris Arcand
description:           'Software developer at HashiCorp 👨‍💻 Formerly: Red Hat, NBC SportsEngine. RubyMN organizer. OSS, distributed teams, and keyboards. I make pointless connections to Minnesota as a Minnesotan does'
location:              Minneapolis, MN
url:                   'https://chrisarcand.com'
google_analytics:      'UA-41741905-2'

author:
  name:                Chris Arcand
  email:               chris@chrisarcand.com
  twitter_username:    chrisarcand
  github_username:     chrisarcand
  linkedin_username:   chrisarcand

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

gist_js_warning: "**Oops! You have Javascript disabled.** I use GitHub Gists to show code on my blog, which regrettably requires JavaScript. I only apologize if you're using an RSS reader :( Please visit the page with Javascript enabled!"

# Build settings
destination:           _site
paginate:              6
permalink:             /:categories/:title/
markdown:              kramdown
highlighter:           rouge
timezone:              America/New_York

kramdown:
  syntax_highlighter:  rouge
  input:               GFM # Github Flavored Markdown
  hard_wrap:           false # do not replace newlines by <br>s

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - src
