# Site settings
title:                 Chris Arcand
description:           'Ruby developer at Red Hat on the open source ManageIQ project. Spends too much money on keyboards and backpacking gear. Made In Minnesota.'
location:              Washington, D.C.
url:                   'https://chrisarcand.com'
# url:                   'http://localhost:4000'
baseurl:               '/'
google_analytics:      'UA-41741905-2'

author:
  name:                Chris Arcand
  email:               chris@chrisarcand.com
  twitter_username:    chrisarcand
  github_username:     chrisarcand
  linkedin_username:   chrisarcand

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

gist_js_warning: "**Oops! You have Javascript disabled.** I use GitHub Gists to show code on my blog, which regrettably requires JavaScript. I only apologize if you're using an RSS reader :( Please visit the page with Javascript enabled!"

# Build settings
destination:           _site
paginate:              6
permalink:             /:categories/:title/
markdown:              kramdown
highlighter:           rouge
timezone:              America/New_York

kramdown:
  syntax_highlighter:  rouge
  input:               GFM # Github Flavored Markdown
  hard_wrap:           false # do not replace newlines by <br>s

gems:
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - src
